# Generated by Django 5.0.3 on 2024-03-21 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
